### ISSUE TITLE
About the computation of ideal_err_ia

### ISSUE THREAD

**Issue by fanjinyong** [lyingCS/Controllable_Multi_Objective_Reranking#1]
```python
                _ideal_err_ia += 1. / ((_i + 1) * (pow(2, _i + 1)))
                _err_ia += 1. / ((_i + 1) * (1 + pow(2, same_cate)))
``` 
should the err_ia be calculated like this??

**Comment by lyingCS** [comment]
Thank you for your interest in our work! Our ERR_IA is calculated based on the definition in https://dl.acm.org/doi/pdf/10.1145/3442381.3449831.

**Comment by fanjinyong** [comment]
Thank you for your reply!!
I understand part of it that"_ideal_err_ia" is the normalized constant as follow:
<img width="338" alt="image" src="https://github.com/lyingCS/Controllable-Multi-Objective-Reranking/assets/72024970/48a444a9-5c83-4f56-ab03-6fc4daf4823d">
but should the y_li in the following formula always be 1？
<img width="190" alt="image" src="https://github.com/lyingCS/Controllable-Multi-Objective-Reranking/assets/72024970/edd84910-64d0-4f56-b0a8-ff476fa74529">

**Comment by lyingCS** [comment]
yeah~the calculation of err-ia in our article is a special form of the definition given above, because our dataset contains only one subtopic for each item, so we can simply simplify it to:
![image](https://github.com/lyingCS/Controllable-Multi-Objective-Reranking/assets/61116720/18f7b3e9-834c-49bf-9c0a-72da9c8e70a2)

**Comment by fanjinyong** [comment]
Thank you for your patient explanation！！！
